<?php

namespace AppBundle\Repository;

/**
 * ArticleImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleImageRepository extends \Doctrine\ORM\EntityRepository
{
}
