<?php

namespace AppBundle\Repository;

/**
 * BioImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BioImageRepository extends \Doctrine\ORM\EntityRepository
{
}
